CREATE CONSTRAINT FOR (p:Person) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT FOR (i:Item) REQUIRE i.id IS UNIQUE;
CREATE CONSTRAINT FOR (r:Report) REQUIRE r.id IS UNIQUE;
CREATE CONSTRAINT FOR (l:Location) REQUIRE l.id IS UNIQUE;
CREATE CONSTRAINT FOR (t:TimeEvent) REQUIRE t.id IS UNIQUE;
CREATE CONSTRAINT FOR (f:Feature) REQUIRE f.id IS UNIQUE;